{% set version = "3.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-seacarb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/seacarb_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/seacarb/seacarb_{{ version }}.tar.gz
  sha256: 8aac7fd60286c31e53ef700150b1539704b55cf22da7183856c4c99934025786

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-solvesaphe
    - r-gsw
    - r-oce
  run:
    - r-base
    - r-solvesaphe
    - r-gsw
    - r-oce

test:
  commands:
    - $R -e "library('seacarb')"           # [not win]
    - "\"%R%\" -e \"library('seacarb')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=seacarb
  license: GPL-2.0-or-later
  summary: Calculates parameters of the seawater carbonate system and assists the design of ocean acidification perturbation experiments.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
