# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ybEICBLKcOm30oFzpOzKUG1T08s3CMd22lUGl4mK50FqKX1DhgRJboeQ/yhEGatlxZxTiAoBU9CYerHaAfcwed/oDGQHqO+3k8iEdUe/hTHjrpDXTfYzhQLLK3e5R5Y6lm8M1aKgRUvEFg1CinfbQApqGsy2fS7SSXKxCFjN7fUbX1iXTW9vzaDEj3oJKMZzWV1qW4f+Ia0q4JoZ9sBK2p2ZNA7J4KM/du8/C2R5uZrU74KJsqeFHd7KZuk41qq9KR1zrQjjjkQkFs3s4PqjSYcUvUyJS/i+WbVTN5P0eG77HKvK4p5WO3pkzRJ05aRPYULB9xw22rVBI3v/yjPfcH91/C0ac9ITHpVbDnqz8++DhRZZwzZz/VKM6FTmJyjT+rrt2NccuEViv1LUEjNZGvqALehvNX0whbISQ/lw/EUjk2I1bK7pd1fUIMSnGdlWGUxBGaBHz/sDi4IuB2ui/qiGEGW3igXqdhVs0pGGEAJOF5txB7wXl1qzI5++zSUQl/hoygVPFdO8kA6h/GdvjylIzm2IMkgT929aoVNfIB94nPQLcTDfh4VLxrhF7T6763MGtMcNu8n2IUdCq4P+ARNYFIOy1iYupy2APUwHl34BxTsglYbR2q0iQFCTDmjVKKp4TAGb0hLQQ/GWWCoy6CZ+eGgWufJdPPabt1M8zOw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
