travis:
  secure:
    BINSTAR_TOKEN: ybEICBLKcOm30oFzpOzKUG1T08s3CMd22lUGl4mK50FqKX1DhgRJboeQ/yhEGatlxZxTiAoBU9CYerHaAfcwed/oDGQHqO+3k8iEdUe/hTHjrpDXTfYzhQLLK3e5R5Y6lm8M1aKgRUvEFg1CinfbQApqGsy2fS7SSXKxCFjN7fUbX1iXTW9vzaDEj3oJKMZzWV1qW4f+Ia0q4JoZ9sBK2p2ZNA7J4KM/du8/C2R5uZrU74KJsqeFHd7KZuk41qq9KR1zrQjjjkQkFs3s4PqjSYcUvUyJS/i+WbVTN5P0eG77HKvK4p5WO3pkzRJ05aRPYULB9xw22rVBI3v/yjPfcH91/C0ac9ITHpVbDnqz8++DhRZZwzZz/VKM6FTmJyjT+rrt2NccuEViv1LUEjNZGvqALehvNX0whbISQ/lw/EUjk2I1bK7pd1fUIMSnGdlWGUxBGaBHz/sDi4IuB2ui/qiGEGW3igXqdhVs0pGGEAJOF5txB7wXl1qzI5++zSUQl/hoygVPFdO8kA6h/GdvjylIzm2IMkgT929aoVNfIB94nPQLcTDfh4VLxrhF7T6763MGtMcNu8n2IUdCq4P+ARNYFIOy1iYupy2APUwHl34BxTsglYbR2q0iQFCTDmjVKKp4TAGb0hLQQ/GWWCoy6CZ+eGgWufJdPPabt1M8zOw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
